eno1220
kss-pc-club/book-2023 pull request #3
Opened 2023-05-03 17:35 UTC by eno1220

- スタイルの変更
  - フォントの変更
  - フォントサイズの変更
  - コードブロックのテーマの変更
  - ヘッダー・フッターの変更
- 目次の追加
- 奥付けの追加
- 執筆者紹介・コメントの追加

以上を行いました。
レビューよろしくお願いします。

2023-05-03 17:55 UTC, Ryoga-exe requested changes

2023-05-03 17:55 UTC, Ryoga-exe commented on scss/theme_common.scss
> +@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700;300&display=swap');
ここで 404 エラーが出る。

`400;700;300` の部分はソートされている必要があるらしく、`300;400;700` と変更しないとまずそう

2023-05-03 18:09 UTC, Ryoga-exe commented
また、gitignore には記載があるが `public/` が ignore されていないような…

キャッシュが残っていそうな気がするので `git rm -r --cached public/book.pdf` などするといいかも

2023-05-19 09:35 UTC, eno1220 commented
ヘッダー・フッダーの変更については、後ほど行うこととし、一旦昨年度のレイアウトをそのまま適用する形に戻しました。

2023-05-19 09:37 UTC, Ryoga-exe approved these changes

2023-05-19 09:42 UTC, merged